import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-base':                    'var(--color-bg-base)',
        'background':                 'var(--color-background)',
        'on-background':              'var(--color-on-background)',
        'surface':                    'var(--color-surface)',
        'on-surface':                 'var(--color-on-surface)',
        'surface-dim':                'var(--color-surface-dim)',
        'surface-bright':             'var(--color-surface-bright)',
        'surface-container-lowest':   'var(--color-surface-container-lowest)',
        'surface-container-low':      'var(--color-surface-container-low)',
        'surface-container':          'var(--color-surface-container)',
        'surface-container-high':     'var(--color-surface-container-high)',
        'surface-container-highest':  'var(--color-surface-container-highest)',
        'surface-variant':            'var(--color-surface-variant)',
        'on-surface-variant':         'var(--color-on-surface-variant)',
        'outline':                    'var(--color-outline)',
        'outline-variant':            'var(--color-outline-variant)',
        
        'primary':                    'var(--color-primary)',
        'on-primary':                 'var(--color-on-primary)',
        'primary-container':          'var(--color-primary-container)',
        'on-primary-container':       'var(--color-on-primary-container)',
        
        'tertiary':                   'var(--color-tertiary)',
        'on-tertiary':                'var(--color-on-tertiary)',
        'tertiary-container':         'var(--color-tertiary-container)',
        'on-tertiary-container':      'var(--color-on-tertiary-container)',

        'error':                      'var(--color-error)',
        'on-error':                   'var(--color-on-error)',
        'error-container':            'var(--color-error-container)',
        'on-error-container':         'var(--color-on-error-container)',

        'primary-fixed':              '#ffdbcc',
        'primary-fixed-dim':          '#ffb695',
        'on-primary-fixed':           '#351000',
        'on-primary-fixed-variant':   '#7b2f00',
        'secondary':                  '#964921',
        'secondary-container':        '#fd9a6c',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#753009',
        'secondary-fixed':            '#ffdbcc',
        'secondary-fixed-dim':        '#ffb695',
        'on-secondary-fixed':         '#351000',
        'on-secondary-fixed-variant': '#77320b',
        'tertiary-fixed':             '#d0e4ff',
        'tertiary-fixed-dim':         '#9ccaff',
        'on-tertiary-fixed':          '#001d35',
        'on-tertiary-fixed-variant':  '#00497b',
        'inverse-surface':            '#2e3134',
        'inverse-on-surface':         '#eff1f5',
        'inverse-primary':            '#ffb695',
      },
      fontFamily: {
        headline: ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        body:     ['var(--font-inter)', 'Inter', 'sans-serif'],
        label:    ['var(--font-inter)', 'Inter', 'sans-serif'],
        mono:     ['var(--font-jetbrains)', 'JetBrains Mono', 'monospace'],
        display:  ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
        sm:      '0.5rem',
        md:      '0.75rem',
      },
      boxShadow: {
        brand: '0 24px 48px -12px rgba(252, 105, 10, 0.35)',
        card:  '0 2px 8px rgba(0,0,0,0.06)',
      },
    },
  },
  plugins: [],
}

export default config
